# Generated by Django 3.2.9 on 2021-12-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_userplaylist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='features_unavailable',
            field=models.BooleanField(default=False),
        ),
    ]
