# Generated by Django 3.2.9 on 2021-12-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_track_features_unavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='userplaylist',
            name='spotify_id',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
