# Generated by Django 3.2.9 on 2021-12-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_userplaylist_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplaylist',
            old_name='user',
            new_name='users',
        ),
    ]
