# Generated by Django 3.2.9 on 2021-12-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userplaylist",
            name="status",
            field=models.CharField(
                choices=[("PR", "Private"), ("PU", "Public"), ("CO", "Collaborative")],
                default="PR",
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
