# Generated by Django 3.2.9 on 2021-12-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_spotifyusercredentials_user'),
        ('music', '0004_auto_20211208_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplaylist',
            name='owner',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.RemoveField(
            model_name='userplaylist',
            name='user',
        ),
        migrations.AddField(
            model_name='userplaylist',
            name='user',
            field=models.ManyToManyField(to='accounts.SpotifyUser'),
        ),
    ]
