# Generated by Django 3.2.9 on 2021-12-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_spotifyusercredentials_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationstate',
            name='state_string',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
