# Generated by Django 3.2.9 on 2021-12-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuser',
            name='spotify_id',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
