# Generated by Django 3.2.9 on 2021-12-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaylist',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
