# Generated by Django 3.2.9 on 2021-12-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_userplaylist_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='track',
            name='artists',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='userplaylist',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
