# Generated by Django 3.2.9 on 2021-12-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20211206_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuser',
            name='spotify_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='userplaylist',
            name='snapshot_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='userplaylist',
            name='spotify_id',
            field=models.CharField(max_length=256),
        ),
    ]
