# Generated by Django 3.2.9 on 2021-12-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='state_string',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
