# Generated by Django 3.2.9 on 2021-12-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_spotifyuser_state_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_string', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='spotifyuser',
            name='state_string',
        ),
    ]
