# Generated by Django 3.2.9 on 2021-12-05 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20211205_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackfeatures',
            name='track',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='server.track'),
        ),
    ]
