name: Review reminders
on:
  schedule:
    - cron: '15 12 */2 * *'
jobs:
  Review-reminders:
    name: Review reminders
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: blombard/review-reminder@v0.2
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        reminder-comment: "Don't forget to review this pull request!"
        days-before-reminder: '4'
